### ISSUE TITLE
Error code 998  when using external::write

### ISSUE THREAD

**Issue by TetrisLitHub** [s3pt3mb3r/toy-arms#11]
I attempted to write a simple external hack (for AssaultCube) following the example given:
```Rust
use toy_arms::external::Process;
use toy_arms::external::{ write };
use toy_arms::VirtualKeyCode;

const HEALTH_OFFSET: u32 = 0xEC;

fn main() {
    let process = Process::from_process_name("ac_client.exe").expect("could not find process");
    println!("{:#?} {:#?} {:#?}", process.process_name, process.process_id, process.process_handle);

    loop {
        write::<u32>(
            process.process_handle,
            process.get_module_base(process.process_name).unwrap() + HEALTH_OFFSET as usize,
            &mut 0x100,
        ).unwrap();

        if toy_arms::detect_keypress(VirtualKeyCode::VK_INSERT) {
            break;
        }
    }
}
```
however this is the output given:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WriteMemoryFailed(UnknownError { error_code: 998 })', src\main.rs:16:11
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library\core\src\result.rs:1785
   3: core::ptr::drop_in_place<std::rt::lang_start<()>::{{closure}}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\RustGameHax.exe` (exit code: 101)
```
I could just be using the library the wrong way though

**Comment by TetrisLitHub** [comment]
I rewrote it as this:
```Rust
use toy_arms::external::Process;
use toy_arms::external::{ write };
use toy_arms::{cast, VirtualKeyCode};

const HEALTH_OFFSET: u32 = 0xEC;

fn main() {
    let process = Process::from_process_name("ac_client.exe").expect("could not find process");
    println!("{:#?} {:#?} {:#?}", process.process_name, process.process_id, process.process_handle);

    loop {
        let health_lmao = cast!(mut process.get_module_base(process.process_name).unwrap() as usize + HEALTH_OFFSET as usize, usize);
        unsafe { *health_lmao = 0x100; }

        if toy_arms::detect_keypress(VirtualKeyCode::VK_INSERT) {
            break;
        }
    }
}
```
and now i get this error instead:
```error: process didn't exit successfully: target\release\RustGameHax.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)```

**Comment by vxcall** [comment]
cast! macro just serves the simple dereference, so in case u faced the access violation, you may have to change protection of the memory page or just the address may be null.
